spring:
  application:
    name: csvReader
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topic-name:
      employee: employee
      assignment: assignment
      project: project
csv:
  path: ${CSV_PATH}
  file-name:
    employee: employee.csv
    assignment: assignment.csv
    project: project.csv
scheduler:
  reader:
    csv-interval: 300000
grpc:
  server:
    port: 9091
    address: "*"
otel:
  traces:
    exporter: otlp
  exporter:
    otlp:
      endpoint: http://localhost:4318
      protocol: http/protobuf
  resource:
    attributes:
      service.name: csvReader
  logs:
    exporter: none
  metrics:
    exporter: none
