spring:
  application:
    name: dbSaver
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jooq:
    sql-dialect: POSTGRES
    database:
      name: org.jooq.meta.postgres.PostgresDatabase
      input-schema: public
      includes: .*
    generator:
      name: org.jooq.codegen.DefaultGenerator
      target:
        package: generated
        directory: target/generated-sources/jooq
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yml
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: db-saver-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
    listener:
      ack-mode: record
    topic-name:
      employee: employee
      assignment: assignment
      project: project
  scheduler:
    reader:
      csv-interval: 300000
grpc:
  client:
    notification-service:
      address: 'static://localhost:9091'
      negotiationType: plaintext
otel:
  traces:
    exporter: otlp
  exporter:
    otlp:
      endpoint: http://localhost:4318
      protocol: http/protobuf
  resource:
    attributes:
      service.name: dbSaver
  logs:
    exporter: none
  metrics:
    exporter: none


